<?php

use Magebit\ProductAttributeFilter\Helper\ProductAttributeFilter;
use Magento\Catalog\Model\Product;


/** @var ProductAttributeFilter $attributes */
$attributes = $this->helper(ProductAttributeFilter::class);

/** @var Product $product */
$product = $attributes->getProduct();

$productDescription = $product->getShortDescription() ? : $attributes->getDescription($product);
$attributeList = $attributes->getFilteredAttributes($product);


?>

<div class="product-attributes">
    <ul>
        <?php foreach ( $attributeList as $item): ?>
            <li>
                <?php
                    echo "<strong>" . $item->getStorelabel() . ":" . "&ensp;</strong>". $item->getFrontend()->getValue($product)
                ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="product-short-info"> <?= $productDescription; ?></div>
</div>
